openapi: 3.0.3
info:
  title: OpenAPI test
  description: This is the first test of open-api generator
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8081/
tags:
  - name: shop
    description: Everything about your Shop
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /order:
    get:
      tags:
        - shop
      summary: Get an order
      description: Get a new order in the store
      operationId: getOrder
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
components:
  schemas:
    Order:
      type: object
      required:
        - "orderId"
        - "customerId"
      properties:
        orderId:
          type: "string"
          format: uuid
        customerId:
          type: "string"
